task-build:
  stage: build
  image: node
  script:
    - mkdir dist
    - cp *.html dist
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  script:
   - mkdir public
   - cp -r dist/* public
  dependencies:
  artifacts:
    paths:
      - public
  only:
    - master